[project]
name = "nlp-homework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "vllm>=0.2.0",
    "torch>=2.0.0",
    "pandas>=1.5.0",
    "rank-bm25>=0.2.2",
    "jieba>=0.42.1",
    "transformers>=4.30.0"
]
